Repository jedrm/MediaGrapher, pull requests merged in 2024-01, with the labels that each got.

#12 Chore: Create docker compose file
  docker-compose.yml
Labels: enhancement

#8 [Feat] Media Module
  .pre-commit-config.yaml
  .pylintrc
  mediagrapher/__init__.py
  mediagrapher/media/__init__.py
  mediagrapher/media/image.py
  mediagrapher/media/media.py
  requirements.txt
  tests/test_image_module.py
  tests/test_images/730.jpg
  tests/test_mediagrapher.py
Labels: enhancement

#20 [Fix] Docker Build
  .github/workflows/development.yml
  Dockerfile
Labels: bug

#21 [Feat] Command-Line Interface
  .github/workflows/development.yml
  .pylintrc
  Dockerfile
  README.md
  mediagrapher.py
  mediagrapher/grapher/matplotlib_grapher.py
  mediagrapher/main.py
Labels: documentation, enhancement
